name: mnemonic_card
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

 # for UI
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter_screenutil: ^5.6.1
  flutter_card_swiper: ^1.2.0
  cached_network_image: ^3.2.3
  lottie: ^2.3.1
  fluttertoast: ^8.2.1
  logger: ^1.3.0
  animate_do: ^3.0.2
  vertical_card_pager: ^1.5.0
  google_nav_bar: ^5.0.6
  # for state managment
  get: ^4.6.5


  # for text to speech
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:

    - assets/images/
    - assets/images/unnamed.jpg
    - assets/lottiefiles/
  #   - images/a_dot_ham.jpeg



  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu.ttf

fonts:
  - family: PTSans
    fonts:
      - asset: assets/fonts/Mali-Regular.ttf




  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
